services:
  bbkkp_sis:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: .
      dockerfile: ./docker/dockerfile/app.Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - bbkkp_network
    ports:
      - "4800:80"

#Docker Networks
networks:
  bbkkp_network:
    external: true
